artist_name = [{text: "Stin", size: 100},
{text: "Pearl Ja", size: 86},
{text: "Andreas Öber", size: 82},
{text: "Tania Mari", size: 70},
{text: "Oscar Peterson Tri", size: 68},
{text: "Megadet", size: 68},
{text: "Jorge Palm", size: 68},
{text: "Supertram", size: 57},
{text: "Seu Jorg", size: 57},
{text: "Pat Metheny Grou", size: 52},
{text: "Damian Erskin", size: 49},
{text: "Incognit", size: 46},
{text: "Ivan Lin", size: 45},
{text: "Pat Methen", size: 44},
{text: "Avishai Cohe", size: 42},
{text: "The John Butler Tri", size: 41},
{text: "Soundgarde", size: 41},
{text: "Maria Rit", size: 40},
{text: "Casiope", size: 40},
{text: "Victor Woote", size: 39},
{text: "Milt Jackso", size: 37},
{text: "Chick Core", size: 33},
{text: "Jamie Cullu", size: 33},
{text: "Jimmy Dludl", size: 33},
{text: "Béla Fleck and the Flecktone", size: 32},
{text: "Michael Jackso", size: 32},
{text: "Bill Evan", size: 32},
{text: "Thievery Corporatio", size: 32},
{text: "Steve Kha", size: 31},
{text: "Horace Silve", size: 30},
{text: "Gary Burto", size: 30},
{text: "Mike Ster", size: 30},
{text: "John Maye", size: 30},
{text: "John Scofiel", size: 30},
{text: "Alicia Key", size: 30},
{text: "Pedro Jói", size: 29},
{text: "Phil Sheera", size: 28},
{text: "Vicente Amig", size: 28},
{text: "Miles Davi", size: 28},
{text: "Ney Matogross", size: 28},
{text: "Fanfare Ciocărli", size: 28},
{text: "Djava", size: 27},
{text: "Rycardo Moren", size: 27},
{text: "Eliane Elia", size: 27},
{text: "Jamiroqua", size: 27},
{text: "Oscar Peterso", size: 27},
{text: "Biréli Lagrèn", size: 26},
{text: "Jafu'meg", size: 26},
{text: "Tomatit", size: 26},
{text: "Anastaci", size: 26},
{text: "Carles Benaven", size: 25},
{text: "Christian McBrid", size: 25},
{text: "Thelonious Mon", size: 25},
{text: "Jeff Richma", size: 25},
{text: "Brian Bromber", size: 25},
{text: "Maria Gad�", size: 25},
{text: "Wes Montgomer", size: 24},
{text: "Paulinho Lêmo", size: 24},
{text: "Bobby Hutcherso", size: 24},
{text: "Dave Hollan", size: 24},
{text: "Van Hale", size: 24},
{text: "Keith Jarret", size: 23},
{text: "Chamba", size: 23},
{text: "Terrence Brewe", size: 23},
{text: "John Patitucc", size: 23},
{text: "Tal Wilkenfel", size: 23},
{text: "Drop Tri", size: 23},
{text: "Jazzinh", size: 23},
{text: "Pat Martin", size: 23},
{text: "Mariz", size: 23},
{text: "Kurt Rosenwinke", size: 23},
{text: "Stan Get", size: 23},
{text: "Alain Caro", size: 23},
{text: "Edward Higginbottom", size: 23},
{text: "Christian Sand", size: 23},
{text: "Joe Sampl", size: 22},
{text: "Lenny Kravit", size: 22},
{text: "Duke Ellingto", size: 21},
{text: "Weather Repor", size: 21},
{text: "Rui Velos", size: 21},
{text: "Pedro Abrunhos", size: 21},
{text: "Jim Hal", size: 21},
{text: "Sérgio Godinh", size: 21},
{text: "James Mood", size: 21},
{text: "Dave Matthews Ban", size: 21},
{text: "Kevin Eubank", size: 21},
{text: "Mafalda Veig", size: 21},
{text: "Aerosmit", size: 20},
{text: "Marc Berthoumieu", size: 20},
{text: "The Flower Kings (Special Edi", size: 20},
{text: "Dee Dee Bridgewate", size: 20},
{text: "Yo-Yo M", size: 20},
{text: "Project Tri", size: 20},
{text: "Jaco Pastoriu", size: 20},
{text: "Wayne Shorte", size: 20},
{text: "Janek Gwizdal", size: 20},
{text: "Esbjörn Svensson Tri", size: 20},
{text: "Lee Ritenou", size: 20},
{text: "Herbie Hancoc", size: 20},
{text: "Diana Kral", size: 20}
];
